// This file has been autogenerated from a class added in the UI designer.

using System;
using AgentieZboruriMPP.domain;
using AgentieZboruriMPP.service;
using Foundation;
using AppKit;

namespace AgentieZboruriMPP
{
	public partial class BuyViewController : NSViewController
	{
		public ServiceMain Service { get; set; }

		public BuyViewController(IntPtr handle) : base(handle)
		{
			Service = new ServiceMain(Helper.UserService, Helper.ZborService, Helper.BiletService);
		}

		partial void handleBuyButton(NSObject sender)
		{
			var id = zborIDField.IntValue;
			var numeClient = numeClientField.StringValue;
			var numeTuristi = numeTuristiField.StringValue;
			var adresa = adresaField.StringValue;
			var nrBilete = nrLocuriField.IntValue;

			try
			{
				if (nrBilete == 0)
					throw new Exception("a");
				Service.addBilet(numeClient, numeTuristi, adresa, nrBilete, id);
				if (nrBilete == 1)
					messageLabel.StringValue = "Ticket successfully purchased!";
				else
					messageLabel.StringValue = "Tickets successfully purchased!";
			}
			catch (Exception e)
			{
				messageLabel.StringValue = "Invalid data!";
			}
			
		}
	}
}
