// This file has been autogenerated from a class added in the UI designer.
using System;
using AgentieZboruriMPP.utils;
using Foundation;
using AppKit;
using AgentieZboruriMPP.service;
using System.Linq;
using System.Threading.Tasks;
using AgentieZboruriMPP.domain;
using System.Timers;


namespace AgentieZboruriMPP
{
	public partial class MainViewController : NSViewController
	{
		public ServiceMain Service { get; set; }
		
		public Zbor Zbor { get; set; }

		public MainViewController(IntPtr handle) : base(handle)
		{
			Service = new ServiceMain(Helper.UserService, Helper.ZborService, Helper.BiletService);
		}

		private ZborTableDataSource ZborTableDataSource { get; set; }
		
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			ZborTableDataSource= new ZborTableDataSource(Service);
			ZborTableView.DataSource = ZborTableDataSource;
			ZborTableView.Delegate = new ZborTableDelegate(ZborTableDataSource);
			reloadZborView();
			//refresh();
		}
		
		public void reloadZborView()
		{
			ZborTableDataSource.Update();
			ZborTableView.ReloadData();
		}

		partial void handleBuyButton(Foundation.NSObject sender)
		{
			PerformSegue("MainToBuySegue", this);
		}
		
		partial void handleLogoutButton(Foundation.NSObject sender)
		{
			View.Window.Close();
		}
		
		public override void PrepareForSegue(NSStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier != "MainToBuySegue") return;
			var buyViewController = (BuyViewController)segue.DestinationController;
			buyViewController.Service = Service;
		}

		public void refresh()
		{
			Timer timer = new Timer(TimeSpan.FromMinutes(0.05).TotalMilliseconds);
			timer.AutoReset = true;
			timer.Elapsed += reloadZborView1;
			timer.Start();
		}

		private void reloadZborView1(object sender, ElapsedEventArgs e)
		{
			reloadZborView();
		}
	}
}
