// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using AgentieZboruriMPP.domain;
using AgentieZboruriMPP.service;
using AgentieZboruriMPP.utils;
using Foundation;
using AppKit;

namespace AgentieZboruriMPP
{
	public partial class SearchViewController : NSViewController
	{
		public ServiceMain Service { get; set; }
		
		public Zbor Zbor { get; set; }
		
		private ZborSearchTableDataSource ZborTableDataSource { get; set; }
		
		public SearchViewController(IntPtr handle) : base(handle)
		{
			Service = new ServiceMain(Helper.UserService, Helper.ZborService, Helper.BiletService);
		}

		private void reloadZborTableView(string destination, DateTime date)
		{
			ZborTableDataSource.Update(destination, date);
			zborTableView.ReloadData();
		}

		partial void handdleSearchButton(Foundation.NSObject sender)
		{
			var destination = destinatieField.StringValue;
			var date = dataPicker.DateValue.ToString();
			List<string> lst = date.Split(' ').ToList();
			DateTime data = Convert.ToDateTime(lst[0]);

			ZborTableDataSource= new ZborSearchTableDataSource(Service, destination, data);
			zborTableView.DataSource = ZborTableDataSource;
			zborTableView.Delegate = new ZborSearchTableDelegate(ZborTableDataSource);

			reloadZborTableView(destination, data);
		}
		
		partial void handleBuyButton(Foundation.NSObject sender)
		{
			PerformSegue("SearchToBuySegue", this);
		}
		
		partial void handleCloseButton(Foundation.NSObject sender)
		{
			View.Window.Close();
		}
		
		public override void PrepareForSegue(NSStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier != "SearchToBuySegue") return;
			var buyViewController = (BuyViewController)segue.DestinationController;
			buyViewController.Service = Service;
		}
	}
}
